/**
 * Cash Cushion vs. Equity Yield Optimizer — Calculation Engine
 *
 * Determines the optimal cash cushion size for a retirement portfolio
 * by factoring in dividend income from the equity portion. The goal is to
 * minimize the amount of cash (which drags growth) while ensuring expenses
 * are covered during a market downturn.
 */

export type CashCushionInput = {
  /** Total portfolio value at the start of retirement (e.g., 1,000,000) */
  portfolioValue: number;
  /** Annual expenses to be covered (e.g., 40,000) */
  annualExpenses: number;
  /** Number of years the cash cushion should cover (e.g., 3) */
  targetSafetyYears: number;
  /** Dividend yield of the equity portfolio as a percentage (e.g., 1.5) */
  equityDividendYield: number;
  /** Yield earned on cash holdings as a percentage (e.g., 4.0) */
  cashYield: number;
};

export type YearBreakdown = {
  /** Year number (1-indexed) */
  year: number;
  /** Dividend income generated by the equity portfolio this year */
  dividendIncome: number;
  /** Withdrawal from the cash cushion this year to cover expenses */
  cashWithdrawal: number;
  /** Cash balance at the start of the year */
  cashBalanceStart: number;
  /** Cash balance at the end of the year (after interest and withdrawal) */
  cashBalanceEnd: number;
};

export type CashCushionResult = {
  /** Naive cash cushion (annualExpenses × targetSafetyYears) */
  naiveCash: number;
  /** Optimized cash cushion (factoring in dividend income and yields) */
  optimizedCash: number;
  /** Capital freed up by using the optimized approach */
  capitalFreedUp: number;
  /** Estimated growth on freed capital over the safety period (7% assumed return) */
  missedGrowthAvoided: number;
  /** Year-by-year breakdown of how expenses are funded */
  annualBreakdown: YearBreakdown[];
};

/**
 * Calculates the optimal cash cushion size using an algebraic PMT-like
 * solution. The formula determines how much cash is needed to cover the
 * shortfall between annual expenses and dividend income over the safety
 * period, accounting for cash earned on the cushion itself.
 *
 * @param input - The cash cushion input parameters
 * @returns A CashCushionResult with naive and optimized values
 */
export function calculateCashCushion(input: CashCushionInput): CashCushionResult {
  const {
    portfolioValue,
    annualExpenses,
    targetSafetyYears,
    equityDividendYield,
    cashYield,
  } = input;

  // Edge case: no portfolio or no expenses
  if (portfolioValue <= 0 || annualExpenses <= 0 || targetSafetyYears <= 0) {
    const emptyBreakdown: YearBreakdown[] = [];
    return {
      naiveCash: 0,
      optimizedCash: 0,
      capitalFreedUp: 0,
      missedGrowthAvoided: 0,
      annualBreakdown: emptyBreakdown,
    };
  }

  // 1. Naive cash cushion
  const naiveCash = annualExpenses * targetSafetyYears;

  // 2. Convert percentages to decimals
  const Y_e = equityDividendYield / 100;
  const Y_c = cashYield / 100;

  // 3. Calculate Annuity Factor (AF)
  let AF: number;
  if (Y_c === 0) {
    AF = targetSafetyYears;
  } else {
    AF = (1 - Math.pow(1 + Y_c, -targetSafetyYears)) / Y_c;
  }

  // 4. Calculate the raw Optimized Cash using the formula:
  //    optimizedCash = ((annualExpenses - (portfolioValue * Y_e)) * AF) / (1 - (Y_e * AF))
  const annualDividendIncome = portfolioValue * Y_e;
  let optimizedCash = ((annualExpenses - annualDividendIncome) * AF) / (1 - (Y_e * AF));

  // 5. Crucial Rule: if dividends alone cover all expenses, optimizedCash = 0
  if (optimizedCash < 0) {
    optimizedCash = 0;
  }

  // 6. Cash drag saved
  const capitalFreedUp = naiveCash - optimizedCash;
  const missedGrowthAvoided = capitalFreedUp * (Math.pow(1 + 0.07, targetSafetyYears) - 1);

  // 7. Year-by-year breakdown
  const annualBreakdown: YearBreakdown[] = [];
  let cashBalance = optimizedCash;

  for (let year = 1; year <= targetSafetyYears; year++) {
    // Dividends from the equity portfolio (fixed, based on initial portfolio)
    const dividendIncome = portfolioValue * Y_e;

    // Shortfall covered by cash
    let cashWithdrawal = annualExpenses - dividendIncome;
    if (cashWithdrawal < 0) {
      cashWithdrawal = 0;
    }

    const cashBalanceStart = cashBalance;

    // Interest earned on the cash cushion
    const interestEarned = cashBalanceStart * Y_c;

    // End balance after interest and withdrawal
    let cashBalanceEnd = cashBalanceStart + interestEarned - cashWithdrawal;
    if (cashBalanceEnd < 0) {
      cashBalanceEnd = 0;
    }

    annualBreakdown.push({
      year,
      dividendIncome,
      cashWithdrawal,
      cashBalanceStart,
      cashBalanceEnd,
    });

    cashBalance = cashBalanceEnd;
  }

  return {
    naiveCash,
    optimizedCash,
    capitalFreedUp,
    missedGrowthAvoided,
    annualBreakdown,
  };
}
